language: objective-c
os: osx
osx_image: xcode12.3
compiler: clang
install: ./travis-install.sh
script: make
after_success: make archive
before_deploy: ./travis-before-deploy.sh
deploy:
- provider: releases
  api_key: "$GH_TOKEN"
  file: "package/Squirrel.pkg"
  skip_cleanup: true
  on:
    tags: false
